spring:
  cloud:
    gateway:
      routes:
        - id: weather_route
          uri: http://send.wxbus163.cn/weather/getCityList
          predicates:
          - Path=/weather/getCityList/**
  main:
    web-application-type: reactive
  datasource:
    # 数据库连接驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据源类型： 默认的是 Hikari
    type: com.zaxxer.hikari.HikariDataSource
    # 数据库连接地址
    url: jdbc:mysql://mysql-3ea6bcea-sensemore.i.aivencloud.com:17890/defaultdb?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    # 数据库连接用户名
    username: avnadmin
    # 数据库连接密码
    password: AVNS_OApBPCrx7zDpxEGs_jZ
  data:
      mongodb:
        database: admin
        host: 127.0.0.1
        port: 27017
        username: root
        password: root
#server:
#  port: 8088

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.server: DEBUG
    reactor.netty.http.client: DEBUG
    com.sensemore.repository: DEBUG
#    org.springframework: DEBUG
  
# mybatis 的配置
mybatis:
  # 配置 mybatis 的xml文件的扫描路径
  mapper-locations: classpath:mybatis/**/*.xml
  # 配置实体类的扫描路径
  type-aliases-package: com.testabc.demo.ssmtest
  configuration:
    # 开启驼峰命名转换
    map-underscore-to-camel-case: true
    # 开启日志
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
